name: mycodeuniverse
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipython==8.20.0
  - ipywidgets==8.1.2
  - matplotlib==3.8.4
  - numpy==1.26.4
  - myst-parser==3.0.1
  - jupyterlab-myst==2.4.2
  - ffmpeg-python==0.2.0